GET http://localhost:9455/user/2

###

GET http://localhost:9455/user/saveUser

###

GET http://localhost:9455/user/testException

###

GET http://localhost:9455/redis/addKey/testKeyMap:key1/1

###
GET http://localhost:9455/redis/getValue/key2

###
GET http://localhost:9455/user/testVoid

###

GET http://localhost:9455/redis/addUser

###
GET http://localhost:9455/redis/getUser

###

# https://blog.csdn.net/johnf_nash/article/details/87526631
GET http://localhost:9455/user/getUserMap/2
###

GET http://localhost:9455/user/userList

###
GET http://localhost:9455/user/search/test

###

GET http://localhost:9455/user/sendMessage/first test Message

###

GET http://localhost:9455/user/sendMessageAsyn/test Message

###

GET http://localhost:9455/user/sendMessageWithConfirm/test Message

###

GET http://localhost:9455/api/mail/sendMail/This is test Text from dev

###
GET http://localhost:9455/api/mail/sendMail/html

###

GET http://localhost:9455/user/sendMessageWithExchange/test Message

###