GET http://localhost:9455/user/2

###

GET http://localhost:9455/user/saveUser

###

GET http://localhost:9455/user/testException

###

GET http://localhost:9455/redis/addKey/key2/3

###
GET http://localhost:9455/redis/getValue/key2

###
GET http://localhost:9455/user/testVoid

###