#spring 配置
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/springbootdemo?useUnicode=true&\
                       characterEncoding=utf-8&allowMultiQueries=true&useSSL=false"
    username: root
    password: 12345
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariPool-Main

server:
  port: 9455

mybatis:
  mapper-locations: classpath:com/boai/springbootdemo/mapper/*.xml
  configuration:
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true
  type-aliases-package: com.boai.springboot2demo.Model